### ISSUE TITLE
NAD C338

### ISSUE THREAD

**Issue by KiboOst** [joopert/nad_receiver#12]
Hi,

Could this work on a NAD C338 once connected to the wifi network ?

I'm looking to possibility of controlling it through python or php/curl. I have not ordered it yet, waiting for such possibility.

Thanks

**Comment by joopert** [comment]
Hi,

I'm afraid I cannot answer this, perhaps @mwsluis can see if the NAD C338 has the same API as the NAD D7050. Not sure where though as I did not find anything on the NAD website.

Otherwise you can try to e-mail NAD and ask if they can provide API documentation for that receiver.

Kind regards

**Comment by KiboOst** [comment]
Thanks joopert. Didn't found his email and can't make issue on its github so don't know how to contact him.

I have contacted NAD support but they aren't the fastest to answer...

There is also an Android and iOS app to control D7050 and C338. I downloaded the apk, and both discuss with tcp, so I guess it should works. All messages are in the apk etc, so I guess I can make a php API to work with it. I will wait for NAD answer even if I'm not sure a technician enough will answer such request.

Thanks,
Kib

**Comment by andreas-amlabs** [comment]
As you said, chances are that it will work. Either with the TCP or the Telnet API. Yes this lib has
two TCP API implementations, TCP and Telnet

My impression with NAD support is really good. Got answer(s) within hours from them.
But they do appreciate clear and precise questions / fault reports

**Comment by mwsluis** [comment]
I am 99% sure the C338 API is the same as the 7050, with the C338 having additional sources. Unfortunately to my knowledge there is no official NAD API documentation for the interface. I had to make it work through other people's work and experimenting with my D7050. I don't own a C338 to experiment with so I'd need official API docs or someone who owns a C338 to test with.

**Comment by KiboOst** [comment]
Thanks both,

Seeing the Nad remote android source code, yes it should work. I will wait a few days to see if support answer, and guess I will order one. I will let you know whatever I do.
I've tested python nad_receiver on Jeedom, but Jeedom python lack the asyncio module (which I put in, but then it lacks selectors, etc...). So I will try python one in my python environment, then I guess I will develop php API for Jeedom.

**Comment by KiboOst** [comment]
Ok, NAD just answered totally out, and no documentation available... No comment

I have ordered it, will let you know.

**Comment by KiboOst** [comment]
ok, got it, but can't get it working...
All setup, wifi, accessible via web (nothing usefull), nad remote app works perfectly.

But python nad_receiver doesn't. Port 50001 isn't opened
I have tried:
_googlezone 10001
related to google cast 8009
spotify 9095
http 80
tcp 53

Port 53 should work, socket seems connected both python/php, but no answer and nothing happend when sending command.

**Comment by mwsluis** [comment]
The d7050 only accepts 1 connection at a time. If the 338 is the same, make sure you close the NAD app first.

**Comment by KiboOst** [comment]
Yes, app and all browser closed. NAD shutoff then on to be sure.
All indicate I'm connected on port 53 but can't get any command to work or any reply.
I tried sniffing the iPhone, but nothing on port 80 and I don't have tool to sniff other ports.

**Comment by KiboOst** [comment]
Ok, seems I will have to return it ...

Is there some initialisation sequence to send over the port ?
How did you find the codes you send ? ex: CMD_ON = "0001020901"

Here is the opened ports I found:

Fing:

53 domaine name server
80 http
8009 ajp13 Apache JServ Protocol 1.3

iNet:

53 domaine name server
80 http
7777 cbt
8008 no description
8009 no description (google cast ?)
8800 Sun Web Server Admin Service
9095 no description (spotify ?)
10001 SCP Configuration (_googlezone ?)
30001 Pago Services 1
38400 no description

Have tried a few, I can connect, but apart a few like 8009 never get an answer.

**Comment by KiboOst** [comment]
A bit more info:
When I try to connect to port 50001, via python or php, I got connection refused.

In your python script, you set powerOn as "0001020901" but decode it from hex before send it. When I print it I got bytes b'\x00\x01\x02\x02\x04\x00\x01\x02\x02\t\x00\x01\x02\x02\n\x00\x01\x02\x02\x03' 

So you don't send plain text but hex bytes ? Or what ?

On port 10001 I got an answer, always being 15030100020246 !?

I've all opened port I have with python, but for example never got status answer (which is combination of different POLL messages).

Where/how did you find these different message to send ?

If you have any help or thing I can test ?

**Comment by KiboOst** [comment]
wow !! big step up !!

With Putty, I connect to IP, Port 30001 with telnet option
Got console
Main.Power=On works !!
Main.xx etc commands works !

**Comment by andreas-amlabs** [comment]
I have no idea and really cannot help without access to the receiver. But a few thoughts

Did you locate open ports with nmap ?
Did you manage to wireshark / tcpdump the android APP ? Perhaps posting the log here could help ?
Port 8008 is sometimes used with websockets. Did you try to connect to the NAD with via ws:// ?
  (long shot, but NAD knows 0 about software APIs)
In case we have more suggestions, what OS do you run ? (the PC I mean)
Logging wireless can be a pain - but one could setup a laptop as AP which would then enable logging
  (I have my NAD on wire, so was no issue for me)

**Comment by andreas-amlabs** [comment]
Hey, you posted while I was writing

Way to go !

**Comment by KiboOst** [comment]
Ahah yes ;-) Sniffing an iPhone other that port 80 (with a proxy it is pretty simple) is harder than I though !

I now have to figure out how to connect and send stream with php like putty do.
Then I will write a complete php API.

Seems Hi-Fi in general live in an old world and don't think a clue about home automation. Shame. But it may be fun finally lol !

**Comment by andreas-amlabs** [comment]
For us curious, what will it run on ? (the php automation code I mean)

I sent in a patch for Home-assistant, but they are really slow on acceptance. (Search the PR section for NAD)

**Comment by KiboOst** [comment]
Err, I guess I have a problem here...

I just run a little test with php socket and it works perfectly in test Jeedom !!
But on my apache server for test (NAS Synology) it doesn't work !!
I will have to get it to work, as developing full API on Jeedom won't be the easier lol !!

Andreas, the main goal is to run a php API on Jeedom to integrate it in scenarios. Actually I use an old NAD 712 on a z-wave plug, but no volume, source etc.
I ever developed APIs for different products and integrate nicely in Jeedom.

**Comment by KiboOst** [comment]
Just to let you know I have a complete php API working perfectly :-)

I'm now integrating it into Jeedom and will finally listen this amp !!

Will publish a repo for it in a few days, time to use it in real life to see if it need debug/improvements

**Comment by KiboOst** [comment]
Ok folks, here is the C338 php API: https://github.com/KiboOst/php-NADC338

I guess I have all official remote functions.
I have found this function that return 0: Main.AnalogGain?
Didn't tried to changed it as it isn't in the official App neither manual etc.

Got it now working in Jeedom, all nice in Jeedom iOS app and HomeKit ! Finally a smart-home amplifier, in 2018 wow ! LOL

**Comment by mindigmarton** [comment]
I've made a C338 compatible library based on this repo. 
It's available on gitlab: https://gitlab.com/mindig.marton/nadtcp

It'd be great if it could be merged, so we don't have to create a third NAD component in home-assistant.
Though the API uses asyncio and no polling, so the interfaces need some tweaking to support both polling and non-polling protocols, so the home assistant component can handle both (as the D7050 cannot handle persistent connections)
