### ISSUE TITLE
Release pinning

### ISSUE THREAD

**Issue by fabaff** [joopert/nad_receiver#14]
`pyserial` is [pinned to 3.2.1](https://github.com/joopert/nad_receiver/blob/9449699d076011caf560d8c4384a9b1bf2512080/setup.py#L11).

Please consider to make it less strict.

For Home Assistant we will update `pyserial` soon to 3.4 and if a person is using the [NAD receiver](https://www.home-assistant.io/components/media_player.nad/) integration along with one that depends on `pyserial` it will not play nice.

**Comment by joopert** [comment]
Sorry for the late reply.
I will look into it, thanks for the notification.
