### ISSUE TITLE
777v3 compatible

### ISSUE THREAD

**Issue by silfa718** [joopert/nad_receiver#16]
Has this been tested to work with 777 v3 AVR?

**Comment by andreas-amlabs** [comment]
No, but it is likely to work. My understanding is that it is the same receiver as the T787
But you should investigate yourself by e.g. get hold of the API documentation for the
T777 v3

**Comment by silfa718** [comment]
Thanks for the reply. I had assumed it would work being that it is similar to the T787, but setting up in Home assistant via TCP, I can see it in the front end, but I'm unable to control it.

**Comment by andreas-amlabs** [comment]
Unable to control it .. any of it ?
I 99.999% of the time only use the On / Off and that works on latest HA. Telnet is real
easy to debug, if you get the loggs then I might be able to help

My config

media_player:
  - platform: nadtelnet
    host: nad.inet
    name: NAD Receiver
    min_volume: -60
    max_volume: -20
    sources:
      1: 'Xbox'
      2: 'TV'
      3: 'Music'

**Comment by silfa718** [comment]
Nothing works pressing the power button from.HA front end has no effect.


Using your above config I get: " platform not found: media_player.nadtelnet"

**Comment by andreas-amlabs** [comment]
Well there we go, my memory ... well, getting old

HA community did not accept my patch for the media_player, so right now you have the nad library part, but not the media component. They complained about there being 3 x platforms for the NAD, they only wanted 1

You should be able to find my patch to HA somewhere.
Seems like I forgot to upload to github, so I did it just now

https://github.com/andreas-amlabs/nadtelnet

Hope that works out for you

**Comment by silfa718** [comment]
Thanks, I assume I put that in like in would with a custom component

**Comment by silfa718** [comment]
I added your component as you described but I am still getting this error:

Platform not found: media_player.nadtelnet

**Comment by andreas-amlabs** [comment]
What about adding some logging ?

A lot of logging
logger:
  default: info
  logs:
    homeassistant.core: debug
    homeassistant.helpers.conditions: debug
    homeassistant.loader: debug
    homeassistant.components.media_player: debug
    homeassistant.components.media_player.nadtelnet: debug


My exact path to the custom component is
/home/homeassistant/.homeassistant/custom_components/media_player/nadtelnet.py

make sure yours match the same logic, you should see the custom directory
in your logs

**Comment by silfa718** [comment]
I'm sure th path is just as you have it.

Logs:

Error loading custom_components.media_player.nadtelnet. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/loader.py", line 166, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/media_player/nadtelnet.py", line 11, in <module>
    from homeassistant.components.media_player import (
ImportError: cannot import name 'SUPPORT_TURN_ON' from 'homeassistant.components.media_player' (/usr/local/lib/python3.7/site-packages/homeassistant/components/media_player/__init__.py)

**Comment by andreas-amlabs** [comment]
Hmm, seems like something has changed in HA, but @ my end things still work

https://community.home-assistant.io/t/breaking-changes-in-custom-media-player/101470/7

Just a minor update though, I will fix this when I run into the issue my self. until then please
fix locally @ your end

**Comment by silfa718** [comment]
I'll give it a shot, thanks for your help.

Just to clarify, in your config where you have host: nad.inet, I would put the IP of the NAD there, correct?

**Comment by andreas-amlabs** [comment]
Yes, nad.inet is my intra-dns name, so ip or dns name will do

**Comment by andreas-amlabs** [comment]
Oh, and plz keeps up updated :)

**Comment by silfa718** [comment]
Updated and works, now I can turn it on and off. Now I can configure the rest of the component.

Do you have T787?

**Comment by andreas-amlabs** [comment]
Nice ! Thanks for the feedback

Yes I have the T787

**Comment by silfa718** [comment]
I wanted to ask you some questions about that, but I don't want to take this too far off topic.

**Comment by andreas-amlabs** [comment]
Fire away, I dont mind.

**Comment by silfa718** [comment]
Do you have an atmos setup with you t787 and are you able to get the NAD app to work with yours?

I was looking to see if there was a way I send you a PM or email or something.

**Comment by silfa718** [comment]
I see this warning in the logs:

"Integrations need to be in their own folder. Change media_player/nadtelnet.py to nadtelnet/media_player.py. This will stop working soon."

Changing the folder and the py file name wouldn't affect anything

**Comment by andreas-amlabs** [comment]
I know very little about how github works, but I think the PM stuff was removed

Anyways, my setup does not use atmos, sonos etc. setup. Currently I just use a 3.0 setup (2 speakers + front. All bi-amp). I do not use the NAD app, since I do not have the BlueOS addon required. I really
dont like buying "fully functional stuff", prefer to build stuff my-self

Ok, thanks for the heads up about the warning. Will look into it when I find the time

Perhaps we should close this issue. You can always open an issue on nadtelnet.py directly with me :)

Please let me know if you find any bugs, it has not gone through a lot of testing !

**Comment by silfa718** [comment]
Yeah if I come across something, I'll let you know. Thanks for the help today.
