### ISSUE TITLE
Integration nadtelnet not found when trying to verify its media_player platform.

### ISSUE THREAD

**Issue by silfa718** [joopert/nad_receiver#17]
After updating to .92 I am getting this error.

**Comment by andreas-amlabs** [comment]
I will look into this when time is given

**Comment by silfa718** [comment]
Thanks

**Comment by andreas-amlabs** [comment]
I dont see this error on 0.92.1, exactly how are you doing to see this issue ?

**Comment by silfa718** [comment]
It happened when I just updated to .92 then when to Configuration > General > Check Config. That is where i saw the error message "Integration nadtelnet not found when trying to verify its media_player platform".

I had to comment it out of my config before it would let me reboot HASS.

I have not had a chance to try it on .92.1

**Comment by andreas-amlabs** [comment]
Tried that, does not appear for me

**Comment by silfa718** [comment]
It must be something up on my side...just updated to .92.1 and I am getting the same error.
