### ISSUE TITLE
What is tag 0.0.12 ? and why is there no 0.0.13 tag ?

### ISSUE THREAD

**Issue by andreas-amlabs** [joopert/nad_receiver#43]
Hi

When checking the nad component in Home Assistant it uses nad_receiver == 0.0.12
But when looking at this page, for nad_receiver, there is no such release ! There is 0.0.11 and 0.1.0

I am missing a 0.0.13 release which includes my fixes for the Telnet open / raise issue (that are on master).
Brief reason for this is that the amount of raises kind of fills my ha.log with output like (1000s of entries !)

homeassistant    | 2020-11-24 21:55:44 ERROR (MainThread) [homeassistant.helpers.entity] Update for media_player.nad_receiver fails
homeassistant    | Traceback (most recent call last):
homeassistant    |   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
homeassistant    |     await self.async_device_update()
homeassistant    |   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 471, in async_device_update
homeassistant    |     await self.hass.async_add_executor_job(self.update)  # type: ignore
homeassistant    |   File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
homeassistant    |     result = self.fn(*self.args, **self.kwargs)
homeassistant    |   File "/usr/src/homeassistant/homeassistant/components/nad/media_player.py", line 179, in update
homeassistant    |     power_state = self._nad_receiver.main_power("?")
homeassistant    |   File "/usr/local/lib/python3.8/site-packages/nad_receiver/__init__.py", line 78, in main_power
homeassistant    |     return self.exec_command('main', 'power', operator, value)
homeassistant    |   File "/usr/local/lib/python3.8/site-packages/nad_receiver/__init__.py", line 341, in exec_command
homeassistant    |     self.telnet.write((''.join(['\r', cmd, '\n']).encode()))
homeassistant    |   File "/usr/local/lib/python3.8/telnetlib.py", line 292, in write
homeassistant    |     self.sock.sendall(buffer)
homeassistant    | BrokenPipeError: [Errno 32] Broken pipe

**Comment by andreas-amlabs** [comment]
@gladhorn  @joopert, hey guy - any insight on this matter ?

**Comment by joopert** [comment]
It seems I did not create a 0.0.12 tag for that release, sorry for that. It was uploaded to pypi though, that is where home assistant collects it from (https://pypi.org/project/nad-receiver/#history) 
After that I went for the 0.1.0 instead of 0.0.13 so for further releases we could adhere to semantic versioning.

After 0.1.0 @gladhorn made more improvements (also including your fixes when looking at the commits), so maybe we should create a new version again and then bump the version at homeassistant to that one.

Any comment on that @gladhorn?

**Comment by andreas-amlabs** [comment]
To me a new release of e.g. 0.1.1 would be really nice :)

**Comment by andreas-amlabs** [comment]
So, how about it ?

**Comment by joopert** [comment]
Hi @andreas-amlabs, as we did not receive a reply from @gladhorn I have created 0.2.0. 

https://pypi.org/project/nad-receiver/#history
https://github.com/joopert/nad_receiver/releases/tag/0.2.0
