### ISSUE TITLE
Tag a new release?

### ISSUE THREAD

**Issue by nickrout** [joopert/nad_receiver#51]
I think it would help to tag a new 0.20.1 release so that it works once again in home assistant.

See discussion here https://community.home-assistant.io/t/media-player-struggles-nad-receiver/325461/

**Comment by joopert** [comment]
Hi, 

I have added another fix (see #52) and uploaded as another version (0.3.0).

You can find it here https://github.com/joopert/nad_receiver/releases/tag/0.3.0 and here
https://pypi.org/project/nad-receiver/0.3.0/

Please note that you will have to make a commit to home assistant to update it to this version.

Thanks for letting us know.
