### ISSUE TITLE
Release to pypi as 0.0.7

### ISSUE THREAD

**Issue by andreas-amlabs** [joopert/nad_receiver#6]
Sorry for opening an issue, but it is not clear to me how to send
user messages @ github

Could you please also upload as 0.0.7 to pypi, would
make my interaction from Home-Assistant so much easier

Thanks

**Comment by joopert** [comment]
Hi, yes, I will create version 0.0.7. 
I will probably do it somewhere this week.

**Comment by joopert** [comment]
@andreas-amlabs I will probably wait till the weekend to upload 0.0.7, hopefully I can include https://github.com/joopert/nad_receiver/pull/4 as well.

**Comment by robhuls** [comment]
I think I have it working, see my comment in PR4.

**Comment by joopert** [comment]
Well, I messed something up, so it is now 0.0.8 :+1:
